---
title: "Assessing & Evaluating SNV calls"
author: "Mark Dunning and Matt Eldridge"
date: '`r format(Sys.time(), "Last modified: %d %b %Y")`'
output: html_document
---

# Introduction

The purpose of this practical is to get you familiar with visualising SNV calls in IGV, and to assess whether they are genuine calls or technical artefacts. 

## Preparation

- Load the Tumour `.bam` file `/home/participant/Course_Materials/data/cell-line/HCC1143.mix1.n20t80.reheader.bam`
- Load the Normal `.bam` file `/home/participant/Course_Materials/data/cell-line/HCC1143.NORMAL.30x.compare.reheader.bam`
- Load the `.vcf` file containing variants called by Caveman for this tumour /normal pair `/home/participant/Course_Materials/Day3/HCC1143_vs_HCC1143_BL.flagged.muts.vcf`

## Variant 1:

`chr8:142486034, C -> T`

[Click here to view in IGV](http://localhost:60151/goto?locus=8:142486034)


<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSe2LQZRl1OE_SwXNc7L5t1YABG1MccnfoUvfnAnIBBbxFaroA/viewform">Click here to vote on your confidence in the call</a>


## Variant 2

`chr14:106471685, G -> A`

[Click here to view in IGV](http://localhost:60151/goto?locus=14:106471685)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSdpcUUnDPwWlHDydXlILnSL-qxhO_y4UkAZccv2l8ONSvbLCg/viewform">Click here to vote on your confidence in the call</a>



## Variant 3

`chr15:91537757, C -> G`

[Click here to view in IGV](http://localhost:60151/goto?locus=15:91537757)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSfqo7oZkTdYNCsF6Xjuvwd47ruqMw7kKPOssBwDV_NVhls3SA/viewform">Click here to vote on your confidence in the call</a>

## Variant 4

`chr22:38120429, T -> C`

[Click here to view in IGV](http://localhost:60151/goto?locus=22:38120429)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSfIDyY_r4GA8plwhOiFrHn64LZ6pbf_YKk-dgFdE8L7oecowQ/viewform">Click here to vote on your confidence in the call</a>



## Variant 5

`chr2:9983580, T -> C`

[Click here to view in IGV](http://localhost:60151/goto?locus=2:9983580)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSfXAJSAmh4QwlH6g-6QSf2Csg_xupu6G48UcDItrctHW2h7Zw/viewform">Click here to vote on your confidence in the call</a>


## Variant 6

`chr1:9633452, G -> A`

[Click here to view in IGV](http://localhost:60151/goto?locus=1:9633452)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSfA-w_-WN34nEhSIaqzdpThmmqDrEIB2YZKcsuSuyUALNL27A/viewform">Click here to vote on your confidence in the call</a>


## Variant 7

`chr3:177090982, A -> G`

[Click here to view in IGV](http://localhost:60151/goto?locus=3:177090982)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSexqNn9I7BaSWvi4b9QzG64xzqERjlojCuao4-4qVzQfA3x1Q/viewform">Click here to vote on your confidence in the call</a>

## Variant 8

`chr15:68175783, A -> G`

[Click here to view in IGV](http://localhost:60151/goto?locus=15:68175783)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSevOKAdDXMQ0IikRJPubQNTkZm3GYMKSdgOpdb7tKP_Ca1w_w/viewform">Click here to vote on your confidence in the call</a>

## Variant 9

`chr3:140281877, A -> C`

[Click here to view in IGV](http://localhost:60151/goto?locus=3:140281877)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLScnl61AlBzaPEx1Zn0fI7jsGksyQXWMb7Kvo6SB4QaKERT6gQ/viewform">Click here to vote on your confidence in the call</a>

## Variant 10

`chr4:22961617, A -> T`

[Click here to view in IGV](http://localhost:60151/goto?locus=4:22961617)

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSctRLQosKFXodunbTWsFnBbNwgjS4fTGQsNh4ky525ZP2-zlA/viewform">Click here to vote on your confidence in the call</a>
